---

- name: Deploying standard configuration to {{ hosts }}
  hosts: '{{ hosts }}'
  gather_facts: yes
  become: true
  become_method: sudo
  roles:
    - basic
    when: hosts is defined
    - reboot
    when: hosts is defined
