---

- name: Verify /home/"{{ user_name }}"/.ssh folder exists
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    recurse: no
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Generate ssh key pair
  shell: ssh-keygen -b 2048 -t rsa -f /home/{{ user_name }}/.ssh/id_rsa -q -N ""

- name: Copying ssh public key {{ ssh.pub_key_path }} from master to {{ hosts }}
  copy:
    src: "{{ ssh.pub_key_path }}"
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
