---

- name: Creating {{ user_name }} group
  group:
   name: "{{ user_name }}"
   state: present

- name: Creating docker group
  group:
    name: docker
    state: present

- name: Creating super user {{ user_name}} for node management
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512')}}"
    group: "{{ user_name }}"
    groups: sudo,docker
    append: yes
    shell: /bin/bash
    system: no
    state: present
