- name: Ensure hostname set to {{ inventory_hostname }}
  hostname:
          name: "{{ inventory_hostname }}"
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

- name: Change entry in /etc/hosts
  lineinfile:
           dest: /etc/hosts
           regexp: '^127\.0\.1\.1[ \t](.*)'
           line: '127.0.1.1 {{ inventory_hostname }}'
           state: present

- name: Ensure hostname is in /etc/hosts
  lineinfile:
           dest: /etc/hosts
           regexp: "^{{ ansible_default_ipv4.address }}.+$"
           line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ inventory_hostname }}"
