- name: Disable swapfile
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove

- name: Enabling cgroups
  shell: sed -i '/cgroup_enable=memory$/!s/$/ cgroup_enable=cpuset cgroup_enable=memory/' /boot/cmdline.txt
