---

- name: Creating {{ user_name }} group
  group:
   name: "{{ user_name }}"
   state: present

- name: Creating docker group
  group:
    name: docker
    state: present

- name: Creating super user {{ user_name}} for node management
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512')}}"
    group: "{{ user_name }}"
    groups: sudo,docker
    append: yes
    shell: /bin/bash
    system: no
    state: present

- name: Verify /home/"{{ user_name }}"/.ssh folder exists
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    recurse: no
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Copying ssh public key {{ ssh.pub_key_path }} from master to {{ hosts }}
  copy:
    src: "{{ ssh.pub_key_path }}"
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
